# Generated by Django 4.2.4 on 2023-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_curso_estudiante_inscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('cuit', models.CharField(max_length=100, verbose_name='CUIT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.CharField(max_length=100, verbose_name='Legajo'),
        ),
    ]
